import csv
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
import pandas as pd
from gspread_dataframe import set_with_dataframe
import os
from dotenv import load_dotenv
import logging
import sys
from utils_df_validation import validate_columns
from df_config import COLUMNS

"""
Script that syncs the spreadsheet maintained on the Google Drive
with the spreadsheets generated by the spiders.
"""

"Dotenv is used to get the Google spreadsheets names and the Google API JSON key."
load_dotenv()

GOOGLE_TOKEN = os.getenv("GOOGLE_JSON_KEY")

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def read_csv(file_name):
    "Read the CSV"
    with open(file_name, newline="") as f:
        return list(csv.reader(f))


def write_csv(file_name, rows):
    "Write data to the CSV"
    with open(file_name, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(rows)


def update_csv(input_file, existing_file):
    """
    This function reads the already existing result CSV
    compares rows with the new output CSV and then removes duplicates
    and, finally, writes the new result CSV.
    """
    input_rows = read_csv(input_file)

    """"
    The existing CSV may have not been created yet, so we need to check if it exists.
    If it doesn't, we just write the input CSV to the existing file.
    """
    if not os.path.exists(existing_file):
        write_csv(existing_file, input_rows)
        return

    input_df = pd.read_csv(input_file)
    input_df = validate_columns(input_df, "camara" if input_file.startswith("camara") else "senado")

    if not os.path.exists(existing_file):
        input_df.to_csv(existing_file, index=False)
        return

    existing_df = pd.read_csv(existing_file)
    existing_df = validate_columns(existing_df, "camara" if existing_file.startswith("camara") else "senado")

    # Remove duplicates
    existing_df = existing_df[~existing_df["id"].isin(input_df["id"])]
    final_df = pd.concat([input_df, existing_df], ignore_index=True)
    final_df.to_csv(existing_file, index=False)


def update_sheet(sheet, file_name, columns):
    """
    This function gets the result CSV that was updated on the update_csv() func
    and then syncs it with the Google spreadsheet.
    """
    # Read the CSV file into a DataFrame
    df = pd.read_csv(file_name)

    # Reindex columns to match predefined list, filling missing ones with None
    df = df.reindex(columns=columns, fill_value=None)

    # Clear the sheet
    sheet.clear()

    # Update the sheet with the DataFrame
    set_with_dataframe(sheet, df)

if __name__ == "__main__":
    if not GOOGLE_TOKEN:
        logger.error("Google API JSON key not found. Halting spreadsheet sync.")
        sys.exit(1)

    "Use creds to create a client to interact with the Google Drive API"
    scope = [
        "https://spreadsheets.google.com/feeds",
        "https://www.googleapis.com/auth/drive",
    ]
    creds = ServiceAccountCredentials.from_json_keyfile_name(
        GOOGLE_TOKEN, scope
    )
    client = gspread.authorize(creds)

    """
    Find a workbook by name and open the first and second sheet
    Make sure you use the right names here.
    """
    "0 refers to first sheet"
    sheet_camara = client.open(os.getenv("SPREADSHEET_NAME")).get_worksheet(0)
    "1 refers to second sheet"
    sheet_senado = client.open(os.getenv("SPREADSHEET_NAME")).get_worksheet(1)


    # Generate the current date in YMD format
    current_date = datetime.now().strftime("%Y%m%d")

    update_csv(f"camara_{current_date}.csv", "camara.csv")
    update_sheet(sheet_camara, "camara.csv", COLUMNS["camara"])

    update_csv(f"senado_{current_date}.csv", "senado.csv")
    update_sheet(sheet_senado, "senado.csv", COLUMNS["senado"])
